services:
  # The api service definition
  server:
    build: .
    container_name: lab1.server
    working_dir: /app
    ports:
      - 5000:5000
    # links:
    #   - "py_client"
    command: sh -c "flask run" # python server.py
    volumes:
      - ./:/app
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: secret
    #   MYSQL_DB: todos

  # # The request client definition
  client:
    build: .
    container_name: lab1.client
    working_dir: /app/client
    restart: on-failure
    depends_on: 
      - server
    links:
      - server
    command: sh -c "python client.py"

# volumes:
#   todo-mysql-data: