services:
  backend:
    build: server
    command: ["flask", "run"]
    volumes:
      - ./server:/backend # mount host folder and the files under:container folder, should create /backend in container first
      
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000" # host:container
  
  frontend:
    build: client
    command: ["python", "client.py"]
    volumes:
      - ./client:/frontend
    depends_on: 
      - backend
